theme = "hakefjord"


[editor]
true-color = true
cursorline = true
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
bufferline = "multiple"
mouse = true
line-number = "relative"
auto-format = true
rulers = [120]

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
character = "╎"
render = true

[editor.file-picker]
hidden = false

[editor.whitespace]
render = "all"

[keys.normal]
# o = ["open_below", "normal_mode"]
# O = ["open_above", "normal_mode"]
esc = ["collapse_selection", "keep_primary_selection"]
V = ["select_mode", "extend_to_line_bounds"]
A-k = "copy_selection_on_prev_line"
A-j = "copy_selection_on_next_line"
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]
C-f = [
  ":new",
  ":insert-output lf-pick",
  ":theme default",
  "select_all",
  "split_selection_on_newline",
  "goto_file",
  "goto_last_modified_file",
  ":buffer-close!",
  ":theme tokyonight",
]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.insert]
j = { k = "normal_mode" }
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal.backspace]
l = { a = ":set line-number absolute", r = ":set line-number relative" }
b = ":run-shell-command zellij run -f -- just build"
r = ":run-shell-command zellij run -f -- just run"
t = ":run-shell-command zellij run -f -- just test"
g = ":run-shell-command zellij run -f -- lazygit"
f = ":run-shell-command zellij run -fc -- broot"

[keys.select]
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
