# Inserts a blank line between shell prompts
#add_newline = true
# format = """[](bold red)[╭----($username@$hostname)----](bold green)"""
right_format = """$kubernetes"""

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[ﰲ](bold green) " # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "

# Disable the package module, hiding it from the prompt completely
#[package]
# disabled = true

[kubernetes]
disabled = false
format = '[$symbol$context \($namespace\)]($style)'

